### ISSUE TITLE
008: peaks_to_subvolumes IndexError

### ISSUE THREAD

**Issue by AilinJ** [xulabs/aitom_doc#10]
@wendingp 

https://github.com/xulabs/aitom_doc/blob/8d7b1f36e2be0535ba779920ad7346089a9418b4/tutorials/008_particle_picking/particle_picking.py#L93

IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

Is it supposed to be as follows?
`a = io_file.read_mrc_data(path)`
 `temp = im_vol_util.cub_img(a)`
 `a_vt = temp['vt'] `
 `d = peaks_to_subvolumes(a_vt, result, 32)`
        

Thanks!

**Comment by wendingp** [comment]
Yes, I haven't updated it yet...
