### ISSUE TITLE
003_simulate_subtomogram.py: module and attribute errors

### ISSUE THREAD

**Issue by AilinJ** [xulabs/aitom_doc#6]
ModuleNotFoundError:
https://github.com/xulabs/aitom_doc/blob/1f7f492d431f7b89d2b01262e69e1a9edc746893/tutorials/003_simulate_subtomogram.py#L16
https://github.com/xulabs/aitom_doc/blob/1f7f492d431f7b89d2b01262e69e1a9edc746893/tutorials/003_simulate_subtomogram.py#L19
https://github.com/xulabs/aitom_doc/blob/1f7f492d431f7b89d2b01262e69e1a9edc746893/tutorials/003_simulate_subtomogram.py#L47

AttributeError:
https://github.com/xulabs/aitom_doc/blob/1f7f492d431f7b89d2b01262e69e1a9edc746893/tutorials/003_simulate_subtomogram.py#L27
https://github.com/xulabs/aitom_doc/blob/1f7f492d431f7b89d2b01262e69e1a9edc746893/tutorials/003_simulate_subtomogram.py#L34

**Comment by AilinJ** [comment]
Cannot find "reconstruction__simple_convolution" module.

**Comment by hrch3n** [comment]
Hi AilinJ. I'm trying to use this script to simulate subtomogram and I got the same error "Cannot find reconstruction__simple_convolution" module". Do you know where I can find this module?

**Comment by AilinJ** [comment]
@hrch3n If I remember it correctly, by the time I closed this issue, the module was still to be created.

**Comment by hrch3n** [comment]
Thanks!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
